language: python
python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install flake8
  - pip install -r requirements.txt
script:
  - flake8 ./src/
  - python -m unittest